language: cpp
sudo: false
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - libstdc++-arm-none-eabi-newlib
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang
before_install:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then brew tap px4/px4; brew update; fi"
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then brew install gcc-arm-none-eabi; fi"
script:
  - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]; then sudo ln -s /usr/bin/python /usr/bin/python2; fi; make all -j3"
notifications:
  email: false

